/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/ti/respostas-prontas/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['editarResposta']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/artigos/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['editarArtigo']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/slas/{prioridade}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['atualizarPolitica']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/calendario/expediente': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['expediente']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/respostas-prontas': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['respostas']
    put?: never
    post: operations['criarResposta']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/filtros-salvos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['filtros']
    put?: never
    post: operations['salvarFiltro']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/artigos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['criarArtigo']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/usuarios/importacao': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['importar']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/categorias': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listar']
    put?: never
    post: operations['criar']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/calendario/feriados': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['adicionarFeriado']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['fila']
    put?: never
    post: operations['criar_1']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/{id}/reabertura': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['reabrir']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/{id}/assumir': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['assumir']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/{chamadoId}/comentarios': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listar_1']
    put?: never
    post: operations['criar_2']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/{chamadoId}/avaliacao': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['buscar']
    put?: never
    post: operations['avaliar']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/{chamadoId}/anexos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listar_2']
    put?: never
    post: operations['enviar']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/dev/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/usuarios/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['atualizar']
    trace?: never
  }
  '/api/v1/ti/admin/categorias/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['atualizar_1']
    trace?: never
  }
  '/api/v1/chamados/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['detalhe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['atualizar_2']
    trace?: never
  }
  '/api/v1/usuarios/busca': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['buscar_1']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/dashboard': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['consultar']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/usuarios': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listar_3']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/slas': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['politicas']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/calendario': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['calendario']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/{id}/historico': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['historico']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/{chamadoId}/linha-do-tempo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listar_4']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/meus': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['meus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categorias': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listar_5']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/csrf': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['csrf']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['config']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/artigos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['artigos']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/artigos/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['artigo']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/anexos/{id}/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['baixar']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/filtros-salvos/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['excluirFiltro']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ti/admin/calendario/feriados/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['removerFeriado']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    RespostaRequest: {
      titulo: string
      texto: string
      ativo?: boolean
    }
    RespostaResponse: {
      /** Format: int64 */
      id?: number
      titulo?: string
      texto?: string
      ativo?: boolean
    }
    ArtigoRequest: {
      titulo: string
      conteudo: string
      /** Format: int64 */
      categoriaId?: number
      publicado?: boolean
    }
    ArtigoResponse: {
      /** Format: int64 */
      id?: number
      titulo?: string
      conteudo?: string
      /** Format: int64 */
      categoriaId?: number
      publicado?: boolean
      /** Format: date-time */
      atualizadoEm?: string
    }
    PoliticaRequest: {
      /** Format: int32 */
      horasPrimeiraResposta?: number
      /** Format: int32 */
      horasResolucao?: number
    }
    Politica: {
      /** @enum {string} */
      prioridade?: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA'
      /** Format: int32 */
      horasPrimeiraResposta?: number
      /** Format: int32 */
      horasResolucao?: number
    }
    Janela: {
      /** Format: int32 */
      diaSemana?: number
      inicio?: string
      fim?: string
    }
    Calendario: {
      expediente?: components['schemas']['Janela'][]
      feriados?: components['schemas']['Feriado'][]
    }
    Feriado: {
      /** Format: int64 */
      id?: number
      /** Format: date */
      data?: string
      descricao?: string
    }
    FiltroRequest: {
      nome: string
      parametros: string
    }
    FiltroResponse: {
      /** Format: int64 */
      id?: number
      nome?: string
      parametros?: string
    }
    ErroLinha: {
      /** Format: int32 */
      linha?: number
      motivo?: string
    }
    RelatorioImportacao: {
      /** Format: int32 */
      importados?: number
      /** Format: int32 */
      rejeitados?: number
      erros?: components['schemas']['ErroLinha'][]
    }
    CriarCategoriaRequest: {
      nome: string
    }
    CategoriaAdminResponse: {
      /** Format: int64 */
      id?: number
      nome?: string
      ativa?: boolean
    }
    FeriadoRequest: {
      /** Format: date */
      data: string
      descricao: string
    }
    CriarChamadoRequest: {
      titulo: string
      descricao: string
      /** Format: int64 */
      categoriaId: number
      /** @enum {string} */
      prioridadeSugerida?: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA'
      /** Format: int64 */
      solicitanteId?: number
    }
    ChamadoResponse: {
      /** Format: int64 */
      id: number
      numero: string
      titulo: string
      descricao: string
      /** Format: int64 */
      solicitanteId: number
      /** Format: int64 */
      abertoPorId: number | null
      /** Format: int64 */
      categoriaId: number
      /** Format: int64 */
      responsavelId: number | null
      /** @enum {string} */
      prioridade: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA'
      /** @enum {string|null} */
      prioridadeSugerida: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA' | null
      /** @enum {string} */
      status:
        | 'ABERTO'
        | 'EM_ATENDIMENTO'
        | 'AGUARDANDO_USUARIO'
        | 'RESOLVIDO'
        | 'FECHADO'
      /** Format: date-time */
      criadoEm: string
      /** Format: date-time */
      atualizadoEm: string
      /** Format: date-time */
      resolvidoEm: string | null
      /** Format: date-time */
      fechadoEm: string | null
      /** Format: date-time */
      primeiraRespostaEm: string | null
      solucao: string | null
      /** Format: date-time */
      prazoResolucao: string | null
      /** Format: date-time */
      prazoPrimeiraResposta: string | null
      /** Format: date-time */
      slaPausadoEm: string | null
      /** Format: int64 */
      version: number
    }
    ReabrirChamadoRequest: {
      /** Format: int64 */
      version: number
    }
    AssumirChamadoRequest: {
      /** Format: int64 */
      version: number
    }
    CriarComentarioRequest: {
      texto: string
      interno?: boolean
    }
    ComentarioResponse: {
      /** Format: int64 */
      id?: number
      /** Format: int64 */
      chamadoId?: number
      /** Format: int64 */
      autorId?: number
      texto?: string
      interno?: boolean
      /** Format: date-time */
      criadoEm?: string
    }
    AvaliarRequest: {
      /** Format: int32 */
      nota?: number
      comentario?: string
    }
    AvaliacaoResponse: {
      /** Format: int64 */
      chamadoId?: number
      /** Format: int32 */
      nota?: number
      comentario?: string
      /** Format: date-time */
      criadoEm?: string
    }
    AnexoResponse: {
      /** Format: int64 */
      id?: number
      /** Format: int64 */
      chamadoId?: number
      /** Format: int64 */
      comentarioId?: number
      nomeOriginal?: string
      tipoMime?: string
      /** Format: int64 */
      tamanho?: number
      /** Format: int64 */
      criadoPor?: number
      interno?: boolean
      /** Format: date-time */
      criadoEm?: string
    }
    LoginRequest: {
      /** Format: email */
      email: string
      nome: string
    }
    UsuarioResponse: {
      /** Format: int64 */
      id?: number
      nome?: string
      email?: string
      /** @enum {string} */
      perfil?: 'FUNCIONARIO' | 'TI_AGENTE' | 'TI_ADMIN'
    }
    AtualizarUsuarioRequest: {
      nome: string
      /** Format: email */
      email: string
      /** @enum {string} */
      perfil: 'FUNCIONARIO' | 'TI_AGENTE' | 'TI_ADMIN'
      ativo?: boolean
    }
    UsuarioAdminResponse: {
      /** Format: int64 */
      id?: number
      nome?: string
      email?: string
      /** @enum {string} */
      perfil?: 'FUNCIONARIO' | 'TI_AGENTE' | 'TI_ADMIN'
      ativo?: boolean
    }
    AtualizarCategoriaRequest: {
      nome: string
      ativa?: boolean
    }
    AtualizarChamadoRequest: {
      /** Format: int64 */
      version: number
      /** @enum {string} */
      status?:
        | 'ABERTO'
        | 'EM_ATENDIMENTO'
        | 'AGUARDANDO_USUARIO'
        | 'RESOLVIDO'
        | 'FECHADO'
      /** @enum {string} */
      prioridade?: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA'
      /** Format: int64 */
      categoriaId?: number
      /** Format: int64 */
      responsavelId?: number
      removerResponsavel?: boolean
      solucao?: string
    }
    UsuarioBuscaResponse: {
      /** Format: int64 */
      id?: number
      nome?: string
      email?: string
      /** @enum {string} */
      perfil?: 'FUNCIONARIO' | 'TI_AGENTE' | 'TI_ADMIN'
    }
    DashboardResponse: {
      /** Format: int64 */
      totalChamados?: number
      /** Format: int64 */
      emAberto?: number
      /** Format: int64 */
      vencidos?: number
      /** Format: int64 */
      vencendo?: number
      /** Format: double */
      tempoMedioResolucaoHoras?: number
      porStatus?: {
        [key: string]: number
      }
      porPrioridade?: {
        [key: string]: number
      }
    }
    PaginaResponseUsuarioAdminResponse: {
      content: components['schemas']['UsuarioAdminResponse'][]
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      /** Format: int64 */
      totalElements: number
      /** Format: int32 */
      totalPages: number
    }
    PaginaResponseChamadoResponse: {
      content: components['schemas']['ChamadoResponse'][]
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      /** Format: int64 */
      totalElements: number
      /** Format: int32 */
      totalPages: number
    }
    HistoricoResponse: {
      /** Format: int64 */
      id?: number
      /** Format: int64 */
      usuarioId?: number
      campo?: string
      valorAnterior?: string
      valorNovo?: string
      /** Format: date-time */
      criadoEm?: string
    }
    PaginaResponseHistoricoResponse: {
      content: components['schemas']['HistoricoResponse'][]
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      /** Format: int64 */
      totalElements: number
      /** Format: int32 */
      totalPages: number
    }
    LinhaTempoItemResponse: {
      /** Format: int64 */
      id?: number
      tipo?: string
      /** Format: int64 */
      autorId?: number
      texto?: string
      status?: string
      /** Format: date-time */
      criadoEm?: string
    }
    PaginaResponseLinhaTempoItemResponse: {
      content: components['schemas']['LinhaTempoItemResponse'][]
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      /** Format: int64 */
      totalElements: number
      /** Format: int32 */
      totalPages: number
    }
    PaginaResponseComentarioResponse: {
      content: components['schemas']['ComentarioResponse'][]
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      /** Format: int64 */
      totalElements: number
      /** Format: int32 */
      totalPages: number
    }
    PaginaResponseAnexoResponse: {
      content: components['schemas']['AnexoResponse'][]
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      /** Format: int64 */
      totalElements: number
      /** Format: int32 */
      totalPages: number
    }
    CategoriaResponse: {
      /** Format: int64 */
      id: number
      nome: string
    }
    CsrfResponse: {
      token?: string
    }
    ConfigResponse: {
      modo?: string
      urlLogin?: string
    }
    PaginaResponseArtigoResponse: {
      content: components['schemas']['ArtigoResponse'][]
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      /** Format: int64 */
      totalElements: number
      /** Format: int32 */
      totalPages: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  editarResposta: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RespostaRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RespostaResponse']
        }
      }
    }
  }
  editarArtigo: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ArtigoRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ArtigoResponse']
        }
      }
    }
  }
  atualizarPolitica: {
    parameters: {
      query?: never
      header?: never
      path: {
        prioridade: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA'
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PoliticaRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Politica']
        }
      }
    }
  }
  expediente: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Janela'][]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Calendario']
        }
      }
    }
  }
  respostas: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RespostaResponse'][]
        }
      }
    }
  }
  criarResposta: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RespostaRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RespostaResponse']
        }
      }
    }
  }
  filtros: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['FiltroResponse'][]
        }
      }
    }
  }
  salvarFiltro: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FiltroRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['FiltroResponse']
        }
      }
    }
  }
  criarArtigo: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ArtigoRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ArtigoResponse']
        }
      }
    }
  }
  importar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          arquivo: string
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RelatorioImportacao']
        }
      }
    }
  }
  listar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CategoriaAdminResponse'][]
        }
      }
    }
  }
  criar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CriarCategoriaRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CategoriaAdminResponse']
        }
      }
    }
  }
  adicionarFeriado: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FeriadoRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Feriado']
        }
      }
    }
  }
  fila: {
    parameters: {
      query?: {
        status?:
          | 'ABERTO'
          | 'EM_ATENDIMENTO'
          | 'AGUARDANDO_USUARIO'
          | 'RESOLVIDO'
          | 'FECHADO'
        prioridade?: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA'
        responsavelId?: number
        categoriaId?: number
        setorId?: number
        desde?: string
        ate?: string
        texto?: string
        semResponsavel?: boolean
        meus?: boolean
        slaVencendo?: boolean
        page?: number
        size?: number
        sort?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PaginaResponseChamadoResponse']
        }
      }
    }
  }
  criar_1: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CriarChamadoRequest']
      }
    }
    responses: {
      /** @description Chamado criado */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ChamadoResponse']
        }
      }
    }
  }
  reabrir: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReabrirChamadoRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ChamadoResponse']
        }
      }
    }
  }
  assumir: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AssumirChamadoRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ChamadoResponse']
        }
      }
    }
  }
  listar_1: {
    parameters: {
      query?: {
        page?: number
        size?: number
      }
      header?: never
      path: {
        chamadoId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PaginaResponseComentarioResponse']
        }
      }
    }
  }
  criar_2: {
    parameters: {
      query?: never
      header?: never
      path: {
        chamadoId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CriarComentarioRequest']
      }
    }
    responses: {
      /** @description Comentário criado */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ComentarioResponse']
        }
      }
    }
  }
  buscar: {
    parameters: {
      query?: never
      header?: never
      path: {
        chamadoId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AvaliacaoResponse']
        }
      }
    }
  }
  avaliar: {
    parameters: {
      query?: never
      header?: never
      path: {
        chamadoId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AvaliarRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AvaliacaoResponse']
        }
      }
    }
  }
  listar_2: {
    parameters: {
      query?: {
        page?: number
        size?: number
      }
      header?: never
      path: {
        chamadoId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PaginaResponseAnexoResponse']
        }
      }
    }
  }
  enviar: {
    parameters: {
      query?: {
        comentarioId?: number
        interno?: boolean
      }
      header?: never
      path: {
        chamadoId: number
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          arquivo: string
        }
      }
    }
    responses: {
      /** @description Anexo armazenado */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AnexoResponse']
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UsuarioResponse']
        }
      }
    }
  }
  atualizar: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AtualizarUsuarioRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UsuarioAdminResponse']
        }
      }
    }
  }
  atualizar_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AtualizarCategoriaRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CategoriaAdminResponse']
        }
      }
    }
  }
  detalhe: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ChamadoResponse']
        }
      }
    }
  }
  atualizar_2: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AtualizarChamadoRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ChamadoResponse']
        }
      }
    }
  }
  buscar_1: {
    parameters: {
      query: {
        texto: string
        somenteTi?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UsuarioBuscaResponse'][]
        }
      }
    }
  }
  consultar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['DashboardResponse']
        }
      }
    }
  }
  listar_3: {
    parameters: {
      query?: {
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PaginaResponseUsuarioAdminResponse']
        }
      }
    }
  }
  politicas: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Politica'][]
        }
      }
    }
  }
  calendario: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Calendario']
        }
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UsuarioResponse']
        }
      }
    }
  }
  historico: {
    parameters: {
      query?: {
        page?: number
        size?: number
      }
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PaginaResponseHistoricoResponse']
        }
      }
    }
  }
  listar_4: {
    parameters: {
      query?: {
        page?: number
        size?: number
      }
      header?: never
      path: {
        chamadoId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PaginaResponseLinhaTempoItemResponse']
        }
      }
    }
  }
  meus: {
    parameters: {
      query?: {
        page?: number
        size?: number
        sort?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PaginaResponseChamadoResponse']
        }
      }
    }
  }
  listar_5: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CategoriaResponse'][]
        }
      }
    }
  }
  csrf: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CsrfResponse']
        }
      }
    }
  }
  config: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ConfigResponse']
        }
      }
    }
  }
  artigos: {
    parameters: {
      query?: {
        texto?: string
        categoriaId?: number
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PaginaResponseArtigoResponse']
        }
      }
    }
  }
  artigo: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ArtigoResponse']
        }
      }
    }
  }
  baixar: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  excluirFiltro: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  removerFeriado: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
