/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/chamados': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['criar']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/dev/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['detalhe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/chamados/meus': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['meus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categorias': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listar']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/csrf': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['csrf']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['config']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    CriarChamadoRequest: {
      titulo: string
      descricao: string
      /** Format: int64 */
      categoriaId: number
      /** @enum {string} */
      prioridadeSugerida?: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA'
      /** Format: int64 */
      solicitanteId?: number
    }
    ChamadoResponse: {
      /** Format: int64 */
      id: number
      numero: string
      titulo: string
      descricao: string
      /** Format: int64 */
      solicitanteId: number
      /** Format: int64 */
      abertoPorId: number | null
      /** Format: int64 */
      categoriaId: number
      /** @enum {string} */
      prioridade: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA'
      /** @enum {string|null} */
      prioridadeSugerida: 'BAIXA' | 'MEDIA' | 'ALTA' | 'CRITICA' | null
      /** @enum {string} */
      status:
        | 'ABERTO'
        | 'EM_ATENDIMENTO'
        | 'AGUARDANDO_USUARIO'
        | 'RESOLVIDO'
        | 'FECHADO'
      /** Format: date-time */
      criadoEm: string
      /** Format: date-time */
      atualizadoEm: string
      /** Format: int64 */
      version: number
    }
    LoginRequest: {
      /** Format: email */
      email: string
      nome: string
    }
    UsuarioResponse: {
      /** Format: int64 */
      id?: number
      nome?: string
      email?: string
      /** @enum {string} */
      perfil?: 'FUNCIONARIO' | 'TI_AGENTE' | 'TI_ADMIN'
    }
    PaginaResponseChamadoResponse: {
      content: components['schemas']['ChamadoResponse'][]
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      /** Format: int64 */
      totalElements: number
      /** Format: int32 */
      totalPages: number
    }
    CategoriaResponse: {
      /** Format: int64 */
      id: number
      nome: string
    }
    CsrfResponse: {
      token?: string
    }
    ConfigResponse: {
      modo?: string
      urlLogin?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  criar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CriarChamadoRequest']
      }
    }
    responses: {
      /** @description Chamado criado */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ChamadoResponse']
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UsuarioResponse']
        }
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UsuarioResponse']
        }
      }
    }
  }
  detalhe: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ChamadoResponse']
        }
      }
    }
  }
  meus: {
    parameters: {
      query?: {
        page?: number
        size?: number
        sort?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PaginaResponseChamadoResponse']
        }
      }
    }
  }
  listar: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CategoriaResponse'][]
        }
      }
    }
  }
  csrf: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CsrfResponse']
        }
      }
    }
  }
  config: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ConfigResponse']
        }
      }
    }
  }
}
