CREATE SEQUENCE chamado_numero_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE setores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL UNIQUE,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE unidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL UNIQUE,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(180) NOT NULL,
  email VARCHAR(254) NOT NULL,
  perfil VARCHAR(20) NOT NULL DEFAULT 'FUNCIONARIO'
    CHECK (perfil IN ('FUNCIONARIO', 'TI_AGENTE', 'TI_ADMIN')),
  setor_id BIGINT REFERENCES setores(id),
  unidade_id BIGINT REFERENCES unidades(id),
  local_trabalho VARCHAR(180),
  ramal VARCHAR(30),
  gestor_id BIGINT REFERENCES usuarios(id),
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  ultimo_login_em TIMESTAMPTZ,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_usuarios_email_ci ON usuarios (lower(email));
CREATE INDEX ix_usuarios_perfil_ativo ON usuarios (perfil, ativo);

CREATE TABLE categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL UNIQUE,
  ativa BOOLEAN NOT NULL DEFAULT TRUE,
  requer_aprovacao BOOLEAN NOT NULL DEFAULT FALSE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sla_politicas (
  prioridade VARCHAR(10) PRIMARY KEY
    CHECK (prioridade IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')),
  horas_primeira_resposta INTEGER NOT NULL CHECK (horas_primeira_resposta > 0),
  horas_resolucao INTEGER NOT NULL CHECK (horas_resolucao > 0),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE expediente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dia_semana SMALLINT NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
  inicio TIME NOT NULL,
  fim TIME NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_expediente_horario CHECK (fim > inicio),
  CONSTRAINT ux_expediente_dia_inicio UNIQUE (dia_semana, inicio)
);

CREATE TABLE feriados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data DATE NOT NULL UNIQUE,
  descricao VARCHAR(180) NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE chamados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(24) NOT NULL UNIQUE,
  titulo VARCHAR(200) NOT NULL,
  descricao TEXT NOT NULL,
  solicitante_id BIGINT NOT NULL REFERENCES usuarios(id),
  aberto_por_id BIGINT REFERENCES usuarios(id),
  responsavel_id BIGINT REFERENCES usuarios(id),
  categoria_id BIGINT NOT NULL REFERENCES categorias(id),
  prioridade VARCHAR(10) NOT NULL DEFAULT 'MEDIA'
    CHECK (prioridade IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')),
  prioridade_sugerida VARCHAR(10)
    CHECK (prioridade_sugerida IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')),
  status VARCHAR(24) NOT NULL DEFAULT 'ABERTO'
    CHECK (status IN ('ABERTO', 'EM_ATENDIMENTO', 'AGUARDANDO_USUARIO', 'RESOLVIDO', 'FECHADO')),
  canal VARCHAR(20) NOT NULL DEFAULT 'PORTAL',
  solucao TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  primeira_resposta_em TIMESTAMPTZ,
  resolvido_em TIMESTAMPTZ,
  fechado_em TIMESTAMPTZ,
  prazo_primeira_resposta TIMESTAMPTZ,
  prazo_resolucao TIMESTAMPTZ,
  sla_pausado_em TIMESTAMPTZ,
  chamado_principal_id BIGINT REFERENCES chamados(id),
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT ck_chamado_nao_duplica_si CHECK (chamado_principal_id IS NULL OR chamado_principal_id <> id)
);
CREATE INDEX ix_chamados_solicitante_criado ON chamados (solicitante_id, criado_em DESC);
CREATE INDEX ix_chamados_fila ON chamados (status, prioridade, criado_em DESC);
CREATE INDEX ix_chamados_responsavel_status ON chamados (responsavel_id, status);
CREATE INDEX ix_chamados_categoria_criado ON chamados (categoria_id, criado_em DESC);
CREATE INDEX ix_chamados_prazo_resolucao ON chamados (prazo_resolucao) WHERE status NOT IN ('RESOLVIDO', 'FECHADO');
CREATE INDEX ix_chamados_sem_responsavel ON chamados (criado_em DESC) WHERE responsavel_id IS NULL AND status NOT IN ('RESOLVIDO', 'FECHADO');

CREATE TABLE comentarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chamado_id BIGINT NOT NULL REFERENCES chamados(id),
  autor_id BIGINT NOT NULL REFERENCES usuarios(id),
  texto TEXT NOT NULL,
  interno BOOLEAN NOT NULL DEFAULT FALSE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_comentarios_chamado_publicos ON comentarios (chamado_id, criado_em, id) WHERE interno = FALSE;
CREATE INDEX ix_comentarios_chamado_todos ON comentarios (chamado_id, criado_em, id);

CREATE TABLE anexos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chamado_id BIGINT NOT NULL REFERENCES chamados(id),
  comentario_id BIGINT REFERENCES comentarios(id),
  nome_original VARCHAR(255) NOT NULL,
  chave_storage VARCHAR(255) NOT NULL UNIQUE,
  tipo_mime VARCHAR(120) NOT NULL,
  tamanho BIGINT NOT NULL CHECK (tamanho > 0),
  criado_por BIGINT NOT NULL REFERENCES usuarios(id),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_anexos_chamado ON anexos (chamado_id);

CREATE TABLE historico_chamado (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chamado_id BIGINT NOT NULL REFERENCES chamados(id),
  usuario_id BIGINT REFERENCES usuarios(id),
  campo VARCHAR(60) NOT NULL,
  valor_anterior TEXT,
  valor_novo TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_historico_chamado ON historico_chamado (chamado_id, criado_em, id);

CREATE TABLE avaliacoes (
  chamado_id BIGINT PRIMARY KEY REFERENCES chamados(id),
  nota SMALLINT NOT NULL CHECK (nota BETWEEN 1 AND 5),
  comentario TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notificacoes_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(60) NOT NULL,
  destinatario VARCHAR(254) NOT NULL,
  payload JSONB NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'PENDENTE'
    CHECK (status IN ('PENDENTE', 'ENVIANDO', 'ENVIADA', 'FALHA')),
  tentativas INTEGER NOT NULL DEFAULT 0 CHECK (tentativas >= 0),
  proxima_tentativa_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_outbox_pendentes ON notificacoes_outbox (proxima_tentativa_em, id) WHERE status IN ('PENDENTE', 'FALHA');

CREATE TABLE shedlock (
  name VARCHAR(64) PRIMARY KEY,
  lock_until TIMESTAMPTZ NOT NULL,
  locked_at TIMESTAMPTZ NOT NULL,
  locked_by VARCHAR(255) NOT NULL
);
