CREATE TABLE artigos_conhecimento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  conteudo TEXT NOT NULL,
  categoria_id BIGINT REFERENCES categorias(id),
  publicado BOOLEAN NOT NULL DEFAULT FALSE,
  autor_id BIGINT NOT NULL REFERENCES usuarios(id),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_artigos_publicados ON artigos_conhecimento (categoria_id, atualizado_em DESC) WHERE publicado = TRUE;
CREATE INDEX ix_artigos_busca ON artigos_conhecimento USING GIN (to_tsvector('portuguese', titulo || ' ' || conteudo)) WHERE publicado = TRUE;

CREATE TABLE respostas_prontas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(120) NOT NULL,
  texto TEXT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  autor_id BIGINT NOT NULL REFERENCES usuarios(id),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_respostas_ativas ON respostas_prontas (titulo) WHERE ativo = TRUE;

CREATE TABLE filtros_salvos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
  nome VARCHAR(80) NOT NULL,
  parametros VARCHAR(1000) NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ux_filtro_usuario_nome UNIQUE (usuario_id, nome)
);
