CREATE TABLE avisos_incidente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(160) NOT NULL,
  mensagem VARCHAR(1000) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  inicio_em TIMESTAMPTZ NOT NULL,
  fim_em TIMESTAMPTZ,
  criado_por BIGINT NOT NULL REFERENCES usuarios(id),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_aviso_periodo CHECK (fim_em IS NULL OR fim_em > inicio_em)
);
CREATE INDEX ix_avisos_ativos ON avisos_incidente (inicio_em DESC, fim_em) WHERE ativo = TRUE;
CREATE INDEX ix_chamados_principal ON chamados (chamado_principal_id) WHERE chamado_principal_id IS NOT NULL;
