package br.com.empresa.helpdesk.compartilhado;

import static org.assertj.core.api.Assertions.assertThat;

import br.com.empresa.helpdesk.anexos.application.StorageService;
import br.com.empresa.helpdesk.compartilhado.retencao.RetencaoService;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class RetencaoServiceTest {
  @Test
  void anonimizaChamadoAntigoERetentaRemocaoDeObjeto() {
    DriverManagerDataSource fonte =
        new DriverManagerDataSource(
            "jdbc:h2:mem:retencao;MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
    JdbcTemplate jdbc = new JdbcTemplate(fonte);
    jdbc.execute(
        "create table usuarios (id bigint generated by default as identity primary key, nome varchar(180), email varchar(254), perfil varchar(20), ativo boolean, criado_em timestamp, atualizado_em timestamp)");
    jdbc.execute(
        "create table chamados (id bigint primary key, status varchar(24), fechado_em timestamp, anonimizado_em timestamp, titulo varchar(200), descricao varchar(1000), solucao varchar(1000), solicitante_id bigint, aberto_por_id bigint, responsavel_id bigint, prioridade_sugerida varchar(10), chamado_principal_id bigint, atualizado_em timestamp, version bigint default 0)");
    jdbc.execute("create table anexos (chamado_id bigint, chave_storage varchar(255))");
    jdbc.execute("create table comentarios (chamado_id bigint, texto varchar(1000))");
    jdbc.execute("create table historico_chamado (chamado_id bigint, valor_novo varchar(1000))");
    jdbc.execute("create table avaliacoes (chamado_id bigint, comentario varchar(1000))");
    jdbc.execute(
        "create table notificacoes_outbox (criado_em timestamp, destinatario varchar(254))");
    jdbc.execute(
        "create table storage_exclusao_pendente (chave_storage varchar(255) primary key, criado_em timestamp default current_timestamp)");
    jdbc.update(
        "insert into usuarios (nome,email,perfil,ativo) values ('Pessoa','pessoa@empresa.com','FUNCIONARIO',true)");
    jdbc.update(
        "insert into chamados (id,status,fechado_em,titulo,descricao,solucao,solicitante_id) values (1,'FECHADO',timestamp '2020-01-01 00:00:00','Pessoa','Dados pessoais','Solução',1)");
    String chave = "00000000-0000-0000-0000-000000000001";
    jdbc.update("insert into anexos (chamado_id,chave_storage) values (1,?)", chave);
    jdbc.update("insert into comentarios (chamado_id,texto) values (1,'Segredo')");
    jdbc.update("insert into historico_chamado (chamado_id,valor_novo) values (1,'Segredo')");
    jdbc.update("insert into avaliacoes (chamado_id,comentario) values (1,'Segredo')");
    jdbc.update(
        "insert into notificacoes_outbox (criado_em,destinatario) values (timestamp '2020-01-01 00:00:00','pessoa@empresa.com')");
    class StorageFalho implements StorageService {
      int tentativas;

      public void gravar(String k, byte[] d, String t) {}

      public byte[] ler(String k) {
        return new byte[0];
      }

      public void remover(String k) {
        if (++tentativas == 1) throw new IllegalStateException("Falha simulada");
      }
    }
    StorageFalho storage = new StorageFalho();
    RetencaoService service =
        new RetencaoService(
            jdbc, storage, Clock.fixed(Instant.parse("2026-09-27T12:00:00Z"), ZoneOffset.UTC), 3);
    assertThat(service.anonimizarLote()).isEqualTo(1);
    assertThat(jdbc.queryForObject("select titulo from chamados where id=1", String.class))
        .isEqualTo("Chamado anonimizado");
    assertThat(jdbc.queryForObject("select count(*) from comentarios", Long.class)).isZero();
    assertThat(jdbc.queryForObject("select count(*) from historico_chamado", Long.class)).isZero();
    assertThat(jdbc.queryForObject("select count(*) from avaliacoes", Long.class)).isZero();
    assertThat(jdbc.queryForObject("select count(*) from notificacoes_outbox", Long.class))
        .isZero();
    assertThat(service.limparObjetosPendentes()).isZero();
    assertThat(jdbc.queryForObject("select count(*) from storage_exclusao_pendente", Long.class))
        .isEqualTo(1);
    assertThat(service.limparObjetosPendentes()).isEqualTo(1);
    assertThat(jdbc.queryForObject("select count(*) from storage_exclusao_pendente", Long.class))
        .isZero();
  }
}
